import type { NextPage } from 'next';
import Head from 'next/head';
import { Fragment, useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import parse from 'html-react-parser';

const Home: NextPage = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] = useState<any>([]);
  console.log('searchResults', searchResults);

  useEffect(() => {
    if (searchTerm.length > 0) {
      fetch(`http://localhost:3001/api/search/guide/${searchTerm}`, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          // 'Access-Control-Allow-Credentials': 'true',
          // Cors: 'no-cors',
          'Content-Type': 'application/json',
          // 'Content-Type': 'application/x-www-form-urlencoded',
        },
      })
        .then((response) => response.json())
        .then((data) => setSearchResults(data))
        .catch((err) => console.log(err));
    }
  }, [searchTerm]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          placeholder="Search a term"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
        {searchResults.response && searchResults.response.length > 0 && (
          <ul>
            {searchResults.response.map((result: any, index: number) => (
              <>
                <li key={index}>
                  <Fragment>{parse(result.text)}</Fragment>
                </li>
                <li key={index}>
                  <Fragment>{parse(result.topic)}</Fragment>
                </li>
              </>
            ))}
          </ul>
        )}
        {searchTerm.length > 0 && !searchResults.response && (
          <div>No Results Found</div>
        )}
      </main>
    </div>
  );
};

export default Home;
