import SearchIcon from '@mui/icons-material/Search';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/Search.module.css';
import parse from 'html-react-parser';

type Response = {
  Id: string;
  Score: number;
  Payload: null;
  Properties: {
    name: string;
    link: string;
    active: string;
  };
};

type Suggestion = {
  incr: boolean;
  payload: string;
  score: number;
  term: string;
};

type SearchResult = {
  total: number;
  response: Response[];
  suggestions: Suggestion[];
};

type Props = {
  apiUrl: string;
  frontedURL: string;
};

const initialResults = {
  total: 0,
  response: [],
  suggestions: [],
};

const Home: NextPage<Props> = ({ apiUrl, frontedURL }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] =
    useState<SearchResult>(initialResults);

  useEffect(() => {
    if (searchTerm.length > 0) {
      fetch(`${apiUrl}/api/search/${searchTerm}`, {
        headers: {
          'Access-Control-Allow-Origin': `${process.env.FE_URL}`,
          'Content-Type': 'application/json',
        },
      })
        .then((response) => response.json())
        .then((data) => setSearchResults(data))
        .catch((err) => console.log(err));
    } else if (searchTerm.length === 0) {
      setSearchResults(initialResults);
    }
  }, [apiUrl, frontedURL, searchTerm]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <div
            className={
              searchTerm.length > 0
                ? styles.searchContainerWithResults
                : styles.searchContainer
            }
          >
            <SearchIcon htmlColor="#72767df9" />
            <input
              title="Search"
              aria-label="Search"
              name="search"
              type="text"
              className={styles.searchBar}
              placeholder="Search a term"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          {searchResults.response && searchResults.response.length > 0 && (
            <ul className={styles.resultsContainer}>
              {searchResults.response
                .slice(0, 5)
                .map((result: Response, index: number) => {
                  return (
                    <a
                      href={result.Properties.link}
                      target="_blank"
                      key={index}
                      className={styles.resultCard}
                      rel="noreferrer"
                    >
                      <li className={styles.flexRow}>
                        <p className={styles.resultType}>
                          {parse(result.Properties.name)}
                        </p>
                      </li>
                      <li className={styles.flexRow}>
                        <p className={styles.resultType}>
                          {result.Properties.active}
                        </p>
                      </li>
                    </a>
                  );
                })}
            </ul>
          )}
          {searchTerm.length > 0 && !searchResults.response && (
            <div className={styles.resultsContainer}>No Results Found</div>
          )}
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const apiUrl = process.env.API_URL;
  const frontedURL = process.env.FE_URL;
  return {
    props: { apiUrl, frontedURL }, // will be passed to the page component as props
  };
}

export default Home;
